export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
// this default export determines where your story goes in the story list
export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body>{children}</body>
    </html>
  )
}
